apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - network-policy.yaml
  - argocd-hpa.yaml

labels:
  - pairs:
      managed-by: argocd
      stack: loyalty-devops
    includeSelectors: false
