apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: loyalty-program
  namespace: argocd
spec:
  description: Loyalty Program Application Project
  sourceRepos:
  - 'https://github.com/Adrian463588/TechnoLoyaltyProgram'
  destinations:
  - namespace: loyalty-prod
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  roles:
  - name: developer
    description: Read-only access for developers
    policies:
    - p, proj:loyalty-program:developer, applications, get, loyalty-program/*, allow
    groups:
    - developers-group
